### ISSUE TITLE
Bug: hex data of Data Directories is incorrect after see Sections Headers 

### ISSUE THREAD

**Issue by marryton007** [jovibor/Pepper#1]
Thanks for your hard working first!  It has a little problem that I met.

version: v0.8.9

It's correct for the first time.
![image](https://user-images.githubusercontent.com/2311328/56861944-79deae80-69d8-11e9-99ed-ccd1a0a558a8.png)

But after check the Sections Headers, like the following action
![image](https://user-images.githubusercontent.com/2311328/56861987-f2456f80-69d8-11e9-8cd4-90841277ab2f.png)

The same data about Data Directories is incorrect.
![image](https://user-images.githubusercontent.com/2311328/56862010-0f7a3e00-69d9-11e9-8c3e-be44b2dc2ddb.png)

Thanks again.

**Comment by jovibor** [comment]
Thanks for your time and reporting.
Indeed there was a inconsistency in the code.
Check the latest version 0.8.11 and see if the problem is gone: https://github.com/jovibor/Pepper/releases/latest
