### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by sherief** [jovibor/Pepper#3]
On a 2x scaling display, all the icons text etc. are displayed at quarter size.

Using 1.2.5 from Releases.

**Comment by jovibor** [comment]
I don't have HiDPI monitor at my hands atm.
But could you try the latest attached version and say if it's any better?

[Pepper_1.2.6(beta).zip](https://github.com/jovibor/Pepper/files/7512294/Pepper_1.2.6.beta.zip)
