### ISSUE TITLE
Imports Directory not showing on a specific exe

### ISSUE THREAD

**Issue by bleriaf** [jovibor/Pepper#7]
i have tested pepper on other application and it seems to show imports directory fine however not on this particular exe. (the imports show fine with pebear for example just not with this)
here's a download to the application: https://ufile.io/x281ac02

**Comment by jovibor** [comment]
Thanks for reporting.
Indeed there was a bug in [libpe](https://github.com/jovibor/libpe) which the **Pepper** is based on.
Now it's fixed, please check the latest version.

I have tested many, many PE files, but still there is always a room for bugs, PE format is very tricky🍺
